version: '3.3'
services:
    phrrs:
        container_name: phrrs
        privileged: true
        ports:
            - ${PORT:-8111}:${PORT:-8111}
        volumes:
            - './${DIR_NAME:-lib}:/opt/phrrs/remote_libraries'
        environment:
            LIBRARY: ${LIBRARY:-tests/test-libraries/ExampleLibrary.php}
            PORT: ${PORT:-8111}
        image: phrrs